Adding flags

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -5,6 +5,7 @@ test_script:
 - sh: |
     RED='\033[0;31m'
     NC='\033[0m'
+    FLAG=false
     for cmd in wget curl 7z 7za ftp lftp tclsh \
     cmake make mvn gradle ant yarn \
     gcc gfortran java javac go nodejs ruby \
@@ -13,10 +14,8 @@ test_script:
     pip easy_install virtualenv python python3 \
     git svn hg
     do 
-      command -v $cmd || echo "$RED$cmd NOT FOUND!$NC"
+      command -v $cmd || { echo -e "$RED$cmd NOT FOUND!$NC"; FLAG=true; }
     done
-    echo "foobar"
-    
-- sh: echo "barfoo"
+    return $FLAG
     
 build: off
