Test easy_install on Ubuntu16 only

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -20,6 +20,12 @@ test_script:
     do 
       command -v $cmd || { echo -e "$RED$cmd NOT FOUND!$NC"; FLAG=true; }
     done
+    if [[ $(lsb_release -sr) == '16.04' ]]; then
+      for easy_install
+      do
+        command -v $cmd || { echo -e "$RED$cmd NOT FOUND!$NC"; FLAG=true; }
+      done
+    fi
     if $FLAG; then
       return 1
     else
